# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               CS675
tagline:             'Distributed Systems (Spring 2020)'
description:         'CS675: Distributed Systems<br>George Mason University'
url:                 http://cs.gmu.edu/~yuecheng
baseurl:             ''

# yue's hack
plugins:
  - jekyll-paginate
#paginate_path: "page:num"
# end of yue's hack

paginate:            5

# About/contact
author:
  name:              Yue Cheng
  url:               https://cs.gmu.edu/~yuecheng
  email:             yuecheng@gmu.edu

# Custom vars
version:             1.0.0


gem:				 liquid
